### ISSUE TITLE
Breaks GitHub when installng combined with isometric contributions plugin.

### ISSUE THREAD

**Issue by Fasani** [g1eny0ung/github-colors-contributions#1]
It look like you also install the isometric contributions plugin?

I would have expected your plugin to only modify colours of both the original contribution visualisation and if installed the isometric contributions plugin?

<img width="320" alt="Screenshot 2020-06-25 at 13 11 40" src="https://user-images.githubusercontent.com/448410/85709330-7088c900-b6e5-11ea-9fbf-532325eae02d.png">

**Comment by g1eny0ung** [comment]
Yep. I added iso as a component of this extension.

Actually, in the beginning, my approach was similar to what you described. But the problem I'm facing is I can't judge the loading order of these two plugins.

Sometimes if the iso extension load before this extension, it's color will not be changed.

**Comment by Fasani** [comment]
You could write a simple polling function or a mutation observer, this way you can wait for DOM to be ready.

**Comment by Fasani** [comment]
As it stands today, every time they change their software you would probably want to include those changes. It just means you need to constantly monitor their repo and that probably won’t be fun or maintainable in the long run for you, just my opinion. Also I installed your software as I felt it might be cool but now I have uninstalled it as it’s broken.

**Comment by g1eny0ung** [comment]
Thx your advice. I think you are right and I thought about how to support change the iso colors.

I will try to determine if you have iso installed and operate it.

**Comment by g1eny0ung** [comment]
@Fasani I released a new version, and now it can coexist with iso.

**Comment by Fasani** [comment]
Just headed out but I will check it out later. Thanks!
